#!/bin/bash
# Swimmy Launch Script with Log Rotation (Gene Kim)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWIMMY_HOME="${SWIMMY_HOME:-$SCRIPT_DIR}"
cd "$SWIMMY_HOME"

# Load Environment Variables
if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

# Dev safety: force-disable Discord notifications after .env is loaded.
if [ "${SWIMMY_FORCE_DISABLE_DISCORD:-0}" = "1" ]; then
    export SWIMMY_DISABLE_DISCORD=1
fi

# Create log directory
mkdir -p logs

# Rotate old log
if [ -f logs/swimmy.log ]; then
    mv logs/swimmy.log logs/swimmy.$(date +%Y%m%d_%H%M%S).log
fi

# Keep only last 7 log files
ls -t logs/swimmy.*.log 2>/dev/null | tail -n +8 | xargs -r rm

# Bootstrap entrypoint
BOOT_FILE="brain.lisp"
BOOT_TEMP=0
if [ ! -f "$BOOT_FILE" ]; then
    echo "[$(date)] [WARN] brain.lisp not found; falling back to ASDF bootstrap." >&2
    BOOT_TEMP=1
    BOOT_FILE="$(mktemp /tmp/swimmy-brain-bootstrap.XXXXXX.lisp)"
    cat > "$BOOT_FILE" <<'LISP'
;;; swimmy-brain fallback bootstrap (generated by run.sh)
(in-package :cl-user)

(require :asdf)
(push (uiop:getcwd) asdf:*central-registry*)

(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))

(format t "~%[LOADER] Loading Swimmy System via ASDF...~%")
(handler-case
    (handler-bind ((style-warning #'muffle-warning)
                   (warning #'muffle-warning))
      (asdf:load-system :swimmy))
  (error (c)
    (format t "~%[FATAL] Failed to load system: ~a~%" c)
    (sb-ext:exit :code 1)))

(uiop:symbol-call :swimmy.main :start-system)
LISP
fi

if [ "$BOOT_TEMP" -eq 1 ]; then
    trap 'rm -f "$BOOT_FILE"' EXIT
fi

# Start Swimmy with logging
# Allow runtime tuning from .env without editing this script again.
SBCL_DYNAMIC_SPACE_MB="${SWIMMY_SBCL_DYNAMIC_SPACE_MB:-6144}"
echo "[$(date)] Starting Swimmy Ver 41.5..."
sbcl --dynamic-space-size "$SBCL_DYNAMIC_SPACE_MB" --noinform --load "$BOOT_FILE" 2>&1 | tee logs/swimmy.log
