;;;; diversity_seed_offline_test.lisp
;;;; Offline, FFI-free regression for the V2d regen ESCAPE ROUTE — diversity-seed
;;;; injection (src/lisp/school/school-seed.lisp).
;;;;
;;;; Native Windows / any host without the sqlite/pzmq FFI DLLs cannot
;;;; `asdf:load-system :swimmy` (see memory native-windows-sbcl-blockers), so this
;;;; harness loads ONLY the pure school-genome.lisp + school-seed.lisp against a
;;;; minimal strategy struct and exercises the REAL inject-diversity-seeds /
;;;; build-diversity-seed / calculate-genetic-distance. It proves the CONSTRUCTION
;;;; contract (flag gating, diversity, and — the honesty crux — that seeds carry NO
;;;; fabricated performance so they MUST pass the honest gate). The end-to-end honest
;;;; scoring (primitive_scan -> Phase-1) is exercised by the WSL daemon_verify harness.
;;;;
;;;; Run from the repo root:
;;;;   sbcl --script tests/diversity_seed_offline_test.lisp
;;;; Exits non-zero on any failure.

(defpackage :swimmy.core (:use :cl) (:export #:*enable-primitive-diversity*))
(in-package :swimmy.core)
(defparameter *enable-primitive-diversity* nil)

(defpackage :swimmy.school (:use :cl :swimmy.core))
(in-package :swimmy.school)

;; Minimal struct — carries every slot the genome + seed functions touch (defaults
;; and slot names match dsl.lisp). copy-strategy / make-strategy / accessors are
;; auto-generated by defstruct, exactly as the real system provides them.
(defstruct strategy
  name indicators entry exit (sl 0.0) (tp 0.0) (volume 0.01)
  (sharpe 0.0) (profit-factor 0.0) (win-rate 0.0) (trades 0) (max-dd 0.0)
  (category :trend) (indicator-type "sma") (pnl-history nil)
  (timeframe 1) (generation 0) (status :active) (status-reason "")
  (tier :incubator) (rank nil) (revalidation-pending nil) (breeding-count 0)
  (regime-intent :unknown) (symbol "USDJPY") (direction :both)
  (hash nil) (oos-sharpe nil) (cpcv-median-sharpe 0.0) (cpcv-pass-rate 0.0)
  (age 0) (immortal nil) (parents nil)
  (band-mult 2.0) (atr-period 14) (atr-barrier-sl 0.0) (atr-barrier-tp 0.0))

;; Stub for the guarded strategy-regime-class call in %seed-base-template.
(defun strategy-regime-class (s) (strategy-category s))

(load (merge-pathnames "src/lisp/school/school-genome.lisp" *default-pathname-defaults*))
(load (merge-pathnames "src/lisp/school/school-seed.lisp" *default-pathname-defaults*))

(defvar *pass* 0)
(defvar *fail* 0)
(defun chk (label ok &optional detail)
  (if ok (progn (incf *pass*) (format t "  PASS  ~a~@[  ~a~]~%" label detail))
         (progn (incf *fail*) (format t "  FAIL  ~a~@[  ~a~]~%" label detail))))
(defmacro with-flag (val &body body) `(let ((*enable-primitive-diversity* ,val)) ,@body))

(format t "~%========== DIVERSITY-SEED ESCAPE-ROUTE OFFLINE TEST ==========~%")

;; A minimal "population" of USDJPY-TREND veterans (the monoculture) with a valid AST.
(defparameter *pop*
  (loop for i from 0 below 5
        collect (make-strategy :name (format nil "USDJPY-TREND-~d" i)
                               :symbol "USDJPY" :category :trend
                               :indicators '((sma 20) (sma 40))
                               :entry '(cross-above (sma 20) (sma 40))
                               :sl 0.005 :tp 0.005 :sharpe 0.6 :cpcv-pass-rate 0.3
                               :trades 300)))

;; ---------------------------------------------------------------------------
;; 1. FLAG-OFF NO-OP (byte-identical legacy: no seeds emitted at all)
;; ---------------------------------------------------------------------------
(with-flag nil
  (chk "flag OFF => inject-diversity-seeds returns NIL"
       (null (inject-diversity-seeds *pop*)))
  (let ((*enable-diversity-seed-injection* nil))
    (with-flag t
      (chk "sub-flag OFF => inject-diversity-seeds returns NIL even under diversity flag"
           (null (inject-diversity-seeds *pop*))))))

;; ---------------------------------------------------------------------------
;; 2. FLAG-ON: seeds are built, and are genuinely diverse
;; ---------------------------------------------------------------------------
(with-flag t
  (let* ((seeds (inject-diversity-seeds *pop*))
         (n (length seeds))
         (syms (remove-duplicates (mapcar #'strategy-symbol seeds) :test #'equal))
         (regs (remove-duplicates (mapcar #'strategy-category seeds)))
         (ntrend (count :trend seeds :key #'strategy-category))
         (nusd (count "USDJPY" seeds :key #'strategy-symbol :test #'equal)))
    (chk "flag ON => seeds emitted" (> n 0) (format nil "~d seeds" n))
    (chk "every seed is NON-USDJPY (escape route target)" (= 0 nusd))
    (chk "seeds only use symbols with real local data"
         (every (lambda (s) (member (strategy-symbol s)
                                    '("EURUSD" "GBPUSD" "EURJPY") :test #'equal)) seeds)
         (format nil "~s" syms))
    (chk "seeds span >=2 symbols (not a mini-monoculture)" (>= (length syms) 2)
         (format nil "~s" syms))
    (chk "seeds span >=2 regimes (TREND + others)" (>= (length regs) 2)
         (format nil "~s" regs))
    (chk "TREND is the MAJORITY regime (escape-route focus)" (> ntrend (/ n 2))
         (format nil "~d/~d TREND" ntrend n))
    (chk "at least one non-USDJPY TREND seed exists (the whole point)"
         (some (lambda (s) (and (not (equal (strategy-symbol s) "USDJPY"))
                                (eq (strategy-category s) :trend))) seeds))))

;; ---------------------------------------------------------------------------
;; 3. HONESTY CRUX: seeds carry NO fabricated performance — must pass the gate
;; ---------------------------------------------------------------------------
(with-flag t
  (let ((seeds (inject-diversity-seeds *pop*)))
    (chk "every seed cpcv-pass-rate = 0.0 (unscored)"
         (every (lambda (s) (= 0.0 (strategy-cpcv-pass-rate s))) seeds))
    (chk "every seed sharpe = 0.0 / pf = 0.0 / trades = 0 (unscored)"
         (every (lambda (s) (and (= 0.0 (strategy-sharpe s))
                                 (= 0.0 (strategy-profit-factor s))
                                 (= 0 (strategy-trades s)))) seeds))
    (chk "every seed oos-sharpe = NIL (never measured)"
         (every (lambda (s) (null (strategy-oos-sharpe s))) seeds))
    (chk "every seed rank = NIL (not pre-promoted)"
         (every (lambda (s) (null (strategy-rank s))) seeds))
    ;; The escape-route invariant: a seed is BELOW the breeding CPCV pre-gate (0.55)
    ;; and BELOW the diverse-robust bar (0.6), so it is injected as an ENTRY but can
    ;; only be counted robust / breed after the HONEST gate raises its cpcv-pass-rate.
    (chk "every seed is below the 0.55 breeding pre-gate AND 0.6 robust bar (entry, not verdict)"
         (every (lambda (s) (< (strategy-cpcv-pass-rate s) 0.55)) seeds))))

;; ---------------------------------------------------------------------------
;; 4. STRUCTURE: TREND seeds are honestly scorable SMA crossovers; regimes map to
;;    primitive_scan's honest primitives {sma,keltner,bollinger,donchian}
;; ---------------------------------------------------------------------------
(with-flag t
  (let* ((seeds (inject-diversity-seeds *pop*))
         (trend (remove-if-not (lambda (s) (eq (strategy-category s) :trend)) seeds))
         (indsym (lambda (s) (car (car (strategy-indicators s))))))
    (chk "every TREND seed's primitive is SMA (primitive_scan scores it as a crossover)"
         (every (lambda (s) (eq 'sma (funcall indsym s))) trend))
    (chk "every seed's primitive is a primitive_scan-honest one"
         (every (lambda (s) (member (funcall indsym s) '(sma keltner bollinger donchian)))
                seeds))
    (chk "every seed has exactly one indicator with an integer period"
         (every (lambda (s) (and (= 1 (length (strategy-indicators s)))
                                 (integerp (second (car (strategy-indicators s))))))
                seeds))))

;; ---------------------------------------------------------------------------
;; 5. B-4 COMPOSITION: the diversity distance SEES the seed as a non-clone of the
;;    USDJPY-TREND monoculture (flag ON), and is blind to it (flag OFF).
;; ---------------------------------------------------------------------------
(let* ((base (first *pop*)))
  (with-flag t
    (let* ((seeds (inject-diversity-seeds *pop*))
           (eurusd-trend (find-if (lambda (s) (and (equal (strategy-symbol s) "EURUSD")
                                                   (eq (strategy-category s) :trend))) seeds))
           (d (calculate-genetic-distance (extract-genome base)
                                          (extract-genome eurusd-trend))))
      (chk "flag ON: EURUSD-TREND seed is NOT a clone of USDJPY-TREND (dist > 0.02 floor)"
           (> d 0.02) (format nil "dist=~,4f" d))
      ;; a non-USDJPY seed must be MORE distant than a same-symbol period tweak
      (let* ((mono-tweak (make-strategy :name "u2" :symbol "USDJPY" :category :trend
                                        :indicators '((sma 22) (sma 44))
                                        :sl 0.005 :tp 0.005))
             (dm (calculate-genetic-distance (extract-genome base)
                                             (extract-genome mono-tweak))))
        (chk "flag ON: cross-symbol seed distance > same-symbol period tweak"
             (> d dm) (format nil "seed=~,4f mono-tweak=~,4f" d dm)))))
  (with-flag nil
    (let* ((*enable-primitive-diversity* nil)
           (seed (make-strategy :name "e" :symbol "EURUSD" :category :trend
                                :indicators '((sma 20) (sma 40)) :sl 0.005 :tp 0.005))
           (d (calculate-genetic-distance (extract-genome base) (extract-genome seed))))
      ;; legacy distance is blind to symbol: same indicators+category+sl+tp => 0.0
      (chk "flag OFF: legacy distance is blind to the seed's symbol (dist ~ 0.0)"
           (< d 0.02) (format nil "dist=~,4f" d)))))

(format t "~%========== RESULT: ~d passed, ~d failed ==========~%" *pass* *fail*)
(when (> *fail* 0) (sb-ext:exit :code 1))
(format t "ALL DIVERSITY-SEED OFFLINE TESTS PASSED~%")
(sb-ext:exit :code 0)
