;;; local-storage-sexp-tests.lisp - S-expression IO tests

(in-package :swimmy.tests)

(deftest test-sexp-io-roundtrip
  (let* ((tmp (merge-pathnames "sexp_io_test.sexp" #P"/tmp/"))
         (payload '((schema_version . 1) (name . "X") (value . 42))))
    (unwind-protect
        (progn
          (swimmy.core:write-sexp-atomic tmp payload)
          (let ((read (swimmy.core:read-sexp-file tmp :package :swimmy.school)))
            (assert-equal payload read)))
      (when (probe-file tmp) (delete-file tmp)))))

(deftest test-backtest-cache-sexp
  (let* ((tmp (merge-pathnames "backtest_cache.sexp" #P"/tmp/"))
         (swimmy.school::*backtest-cache-file* (namestring tmp))
         (swimmy.school::*backtest-cache* (make-hash-table :test 'equal)))
    (setf (gethash "StratA" swimmy.school::*backtest-cache*)
          (list :timestamp 123 :result '(:sharpe 1.0 :trades 10)))
    (swimmy.school::save-backtest-cache)
    (let* ((sexp (swimmy.core:read-sexp-file tmp :package :swimmy.school))
           (schema (and sexp (find-if (lambda (pair)
                                        (and (consp pair)
                                             (string-equal "SCHEMA_VERSION" (symbol-name (car pair)))))
                                      sexp))))
      (assert-true schema "Expected schema_version in S-expression file")
      (assert-equal 1 (cdr schema)))
    (clrhash swimmy.school::*backtest-cache*)
    (swimmy.school::load-backtest-cache)
    (let ((cached (gethash "StratA" swimmy.school::*backtest-cache*)))
      (assert-true cached)
      (assert-equal 1.0 (getf (getf cached :result) :sharpe)))
    (when (probe-file tmp) (delete-file tmp))))

(deftest test-telemetry-sexp
  (let* ((tmp (merge-pathnames "system_metrics.sexp" #P"/tmp/"))
         (swimmy.school::*telemetry-file* (namestring tmp)))
    (swimmy.school::save-telemetry-sexp (list :heap 1 :strategy-count 2))
    (let* ((sexp (swimmy.core:read-sexp-file tmp :package :swimmy.school))
           (schema (and sexp (find-if (lambda (pair)
                                        (and (consp pair)
                                             (string-equal "SCHEMA_VERSION" (symbol-name (car pair)))))
                                      sexp))))
      (assert-true schema "Expected schema_version in telemetry S-expression"))
    (when (probe-file tmp) (delete-file tmp))))

(deftest test-telemetry-sexp-includes-notifier-metrics
  (let* ((tmp (merge-pathnames "system_metrics.sexp" #P"/tmp/"))
         (notifier (merge-pathnames "notifier_metrics.sexp" #P"/tmp/"))
         (swimmy.school::*telemetry-file* (namestring tmp))
         (notifier-file-sym (intern "*NOTIFIER-METRICS-FILE*" :swimmy.school))
         (orig-notifier (and (boundp notifier-file-sym) (symbol-value notifier-file-sym))))
    (unwind-protect
        (progn
          (setf (symbol-value notifier-file-sym) (namestring notifier))
          (let* ((ksv (intern "SCHEMA_VERSION" :swimmy.school))
                 (kts (intern "TIMESTAMP" :swimmy.school))
                 (kql (intern "QUEUE_LEN" :swimmy.school))
                 (kdr (intern "DROPS" :swimmy.school))
                 (ker (intern "ERRORS" :swimmy.school))
                 (payload (list (cons ksv 1)
                                (cons kts 123)
                                (cons kql 5)
                                (cons kdr 2)
                                (cons ker 1))))
            (swimmy.core:write-sexp-atomic notifier payload))
          (swimmy.school::save-telemetry-sexp (list :heap 1 :strategy-count 2))
          (let* ((sexp (swimmy.core:read-sexp-file tmp :package :swimmy.school))
                 (kq (find-symbol "NOTIFIER_QUEUE_LEN" :swimmy.school))
                 (kd (find-symbol "NOTIFIER_DROPS" :swimmy.school))
                 (ke (find-symbol "NOTIFIER_ERRORS" :swimmy.school))
                 (q (and kq (assoc kq sexp)))
                 (d (and kd (assoc kd sexp)))
                 (e (and ke (assoc ke sexp))))
            (assert-true q "Expected notifier_queue_len in system_metrics.sexp")
            (assert-true d "Expected notifier_drops in system_metrics.sexp")
            (assert-true e "Expected notifier_errors in system_metrics.sexp")
            (assert-equal 5 (cdr q))
            (assert-equal 2 (cdr d))
            (assert-equal 1 (cdr e))))
      (if orig-notifier
          (setf (symbol-value notifier-file-sym) orig-notifier)
          (ignore-errors (makunbound notifier-file-sym)))
      (when (probe-file tmp) (delete-file tmp))
      (when (probe-file notifier) (delete-file notifier)))))

(deftest test-live-status-sexp
  (let* ((tmp (merge-pathnames "live_status.sexp" #P"/tmp/"))
         (swimmy.shell::*live-status-path* (namestring tmp)))
    (swimmy.shell::save-live-status)
    (let* ((sexp (swimmy.core:read-sexp-file tmp :package :swimmy.main))
           (schema (and sexp (find-if (lambda (pair)
                                        (and (consp pair)
                                             (string-equal "SCHEMA_VERSION" (symbol-name (car pair)))))
                                      sexp)))
           (daily (and sexp (find-if (lambda (pair)
                                       (and (consp pair)
                                            (string-equal "DAILY_PNL" (symbol-name (car pair)))))
                                     sexp))))
      (assert-true schema "Expected schema_version in live status S-expression")
      (assert-true daily "Expected daily_pnl in live status S-expression"))
    (when (probe-file tmp) (delete-file tmp))))
