;;; strategies-recruits.lisp
;;; GENERATED BY ANTI-GRAVITY RECRUITMENT PROTOCOL
;;; New strategies recruited from the Evolutionary Gap.

(in-package :swimmy.school)

(defun get-recruit-strategies ()
  (list
      (make-strategy :name "RECRUIT-RND-1768786246-12"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0340 :tp 0.1090 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768786212-2"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0990 :tp 0.0140 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768786181-0"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0270 :tp 0.0790 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768786153-0"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0810 :tp 0.0930 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768786124-15"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0610 :tp 0.0910 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768786089-1"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0750 :tp 0.1040 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768786068-20"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0310 :tp 0.0520 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768786032-11"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0230 :tp 0.0550 :volume 0.01
        :category :recruit :timeframe 240)
      (make-strategy :name "RECRUIT-RND-1768786001-5"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0810 :tp 0.0940 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768785966-5"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0740 :tp 0.1110 :volume 0.01
        :category :recruit :timeframe 60)
      (make-strategy :name "RECRUIT-RND-1768785939-13"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0630 :tp 0.0980 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768785906-1"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0440 :tp 0.0890 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768785882-1"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0420 :tp 0.1150 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768785855-29"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0540 :tp 0.1410 :volume 0.01
        :category :recruit :timeframe 30)
      (make-strategy :name "RECRUIT-RND-1768785820-0"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0740 :tp 0.1400 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768785790-8"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0330 :tp 0.1210 :volume 0.01
        :category :recruit :timeframe 10080)
      (make-strategy :name "RECRUIT-RND-1768785757-2"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0570 :tp 0.0370 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768785725-5"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0650 :tp 0.0240 :volume 0.01
        :category :recruit :timeframe 1440)
      (make-strategy :name "RECRUIT-RND-1768785700-4"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0320 :tp 0.1420 :volume 0.01
        :category :recruit :timeframe 240)
      (make-strategy :name "RECRUIT-RND-1768785669-37"
        :indicators '((sma 5) (sma 20))
        :entry '(cross-above sma-5 sma-20)
        :exit '(cross-below sma-5 sma-20)
        :sl 0.0410 :tp 0.1420 :volume 0.01
        :category :recruit :timeframe 10080)))
