(in-package :swimmy.main)

(defun internal-process-msg (msg)
  (handler-case
      (if (and (> (length msg) 0) (char= (char msg 0) #\())
          (let* ((sexp (read-from-string msg))
                 (type (cdr (assoc 'type sexp))))
            (cond
              ((member type '(backtest-result :backtest-result) :test #'eq)
               (let* ((result (cdr (assoc 'result sexp)))
                      (full-name (cdr (assoc 'strategy_name result)))
                      (sharpe (float (or (cdr (assoc 'sharpe result)) 0.0)))
                      (trades (or (cdr (assoc 'trades result)) 0))
                      (pnl (float (or (cdr (assoc 'pnl result)) 0.0)))
                      (win-rate (float (or (cdr (assoc 'win_rate result)) 0.0)))
                      (profit-factor (float (or (cdr (assoc 'profit_factor result)) 0.0)))
                      (max-dd (float (or (cdr (assoc 'max_dd result)) 1.0)))
                      (is-rr (search "-RR" full-name))
                      (is-qual (search "-QUAL" full-name))
                      (name (cond (is-rr (subseq full-name 0 is-rr))
                                  (is-qual (subseq full-name 0 is-qual))
                                  (t full-name)))
                      (metrics (list :sharpe sharpe :trades trades :pnl pnl :win-rate win-rate :profit-factor profit-factor :max-dd max-dd)))
                 (swimmy.school:cache-backtest-result name metrics)
                 (swimmy.school:apply-backtest-result name metrics)
                 (cond
                   (is-qual
                    (push (cons name metrics) swimmy.globals:*qual-backtest-results-buffer*)
                    (let ((count (length swimmy.globals:*qual-backtest-results-buffer*))
                          (expected swimmy.globals:*qual-expected-backtest-count*))
                      (when (and (> expected 0) (>= count (max 1 (floor (* expected 0.9)))))
                        (swimmy.core:notify-backtest-summary :qual))))
                   (t
                    (push (cons name metrics) swimmy.globals:*rr-backtest-results-buffer*)
                    (let ((count (length swimmy.globals:*rr-backtest-results-buffer*))
                          (expected swimmy.globals:*rr-expected-backtest-count*))
                      (when (and (> expected 0) (>= count (max 1 (floor (* expected 0.9)))))
                        (swimmy.core:notify-backtest-summary :rr)))))
                 (when (fboundp 'swimmy.school:process-wfv-result)
                   (swimmy.school:process-wfv-result name metrics))))
              ((member type '(cpcv-result :cpcv-result) :test #'eq)
               (let* ((result (cdr (assoc 'result sexp)))
                      (name (cdr (assoc 'strategy_name result)))
                      (median (cdr (assoc 'median_sharpe result)))
                      (paths (cdr (assoc 'path_count result)))
                      (passed (cdr (assoc 'passed_count result)))
                      (failed (cdr (assoc 'failed_count result)))
                      (pass-rate (cdr (assoc 'pass_rate result)))
                      (is-passed (cdr (assoc 'is_passed result))))
                 (let ((result-plist (list :strategy-name name :median-sharpe median :path-count paths 
                                           :passed-count passed :failed-count failed :pass-rate pass-rate :is-passed is-passed)))
                   (swimmy.core:notify-cpcv-result result-plist)
                   (push result-plist swimmy.globals:*cpcv-results-buffer*)
                   (let ((count (length swimmy.globals:*cpcv-results-buffer*))
                         (expected swimmy.globals:*expected-cpcv-count*))
                     (when (and (> expected 0) (>= count (max 1 (floor (* expected 0.9)))))
                       (swimmy.core:notify-cpcv-summary)))
                   (when (and is-passed (not (eq is-passed 'nil)))
                     (let ((strat (or (find name swimmy.school::*strategy-knowledge-base* :key #'swimmy.school:strategy-name :test #'string=)
                                      (find name swimmy.globals:*evolved-strategies* :key #'swimmy.school:strategy-name :test #'string=))))
                       (when strat
                         (setf (swimmy.school:strategy-cpcv-median-sharpe strat) median)
                         (setf (swimmy.school:strategy-cpcv-pass-rate strat) pass-rate)
                         (swimmy.school:upsert-strategy strat)
                         (if (swimmy.school:check-rank-criteria strat :S)
                             (swimmy.school:ensure-rank strat :S "CPCV Passed and Criteria Met")
                             (format t "[CPCV] Strategy ~a passed CPCV but failed overall S-Rank criteria.~%" name))))))))
              (t nil)))
          (let* ((json (jsown:parse msg)) (type (jsown:val json "type")))
            (cond
              ((string= type swimmy.core:+MSG-TICK+) 
               (swimmy.main:update-candle (jsown:val json "bid") (jsown:val json "symbol"))
               (when (fboundp 'swimmy.school:process-category-trades)
                 (swimmy.school:process-category-trades (jsown:val json "symbol") (jsown:val json "bid") (jsown:val json "ask")))
               (when (fboundp 'swimmy.shell:save-live-status) (swimmy.shell:save-live-status))
               (when (fboundp 'swimmy.shell:send-periodic-status-report)
                 (swimmy.shell:send-periodic-status-report (jsown:val json "symbol") (jsown:val json "bid")))
               (handler-case (when (fboundp 'swimmy.school:continuous-learning-step) (swimmy.school:continuous-learning-step)) (error () nil)))
              ((string= type swimmy.core:+MSG-HEARTBEAT+)
               (setf swimmy.globals:*last-guardian-heartbeat* (get-universal-time)))
              ((string= type swimmy.core:+MSG-ACCOUNT-INFO+)
               (swimmy.executor:process-account-info json))
              ((string= type "SYSTEM_COMMAND")
               (let ((action (jsown:val json "action")))
                 (cond
                   ((string= action "REPORT_STATUS") (swimmy.school:report-active-positions))
                   ((string= action "BACKTEST_SUMMARY") (swimmy.core:notify-backtest-summary)))))
              ((string= type "BACKTEST_RESULT")
               (let* ((result (jsown:val json "result"))
                      (full-name (jsown:val result "strategy_name"))
                      (sharpe (float (or (handler-case (jsown:val result "sharpe") (error () 0.0)) 0.0)))
                      (is-rr (search "-RR" full-name))
                      (is-qual (search "-QUAL" full-name))
                      (name (cond (is-rr (subseq full-name 0 is-rr))
                                  (is-qual (subseq full-name 0 is-qual))
                                  (t full-name))))
                 (cond
                   (is-qual
                    (push (cons name (list :sharpe sharpe)) swimmy.globals:*qual-backtest-results-buffer*)
                    (let ((count (length swimmy.globals:*qual-backtest-results-buffer*))
                          (expected swimmy.globals:*qual-expected-backtest-count*))
                      (when (and (> expected 0) (>= count (max 1 (floor (* expected 0.9)))))
                        (swimmy.core:notify-backtest-summary :qual))))
                   (t
                    (push (cons name (list :sharpe sharpe)) swimmy.globals:*rr-backtest-results-buffer*)
                    (let ((count (length swimmy.globals:*rr-backtest-results-buffer*))
                          (expected swimmy.globals:*rr-expected-backtest-count*))
                      (when (and (> expected 0) (>= count (max 1 (floor (* expected 0.9)))))
                        (swimmy.core:notify-backtest-summary :rr)))))))
              (t nil))))
    (error (e) (format t "[L] Msg Error: ~a" e) nil)))

(defun process-msg (msg) (internal-process-msg msg))
