(defun transform-cross-calls-helper (expr pkg)
  (flet ((add-prev-suffix (sym)
           (if (symbolp sym)
               (intern (format nil "~a-PREV" (symbol-name sym)) pkg)
               sym)))
    (cond
      ((atom expr) expr)
      ((and (listp expr) 
            (member (car expr) '(cross-above cross-below))
            (= (length expr) 3))
       (let ((fn (first expr))
             (a (second expr))
             (b (third expr)))
         (list fn 
               (if (symbolp a) a (eval a)) 
               (if (symbolp b) b (eval b)) 
               (if (symbolp a) (add-prev-suffix a) (eval a)) 
               (if (symbolp b) (add-prev-suffix b) (eval b)))))
      (t (mapcar (lambda (e) (transform-cross-calls-helper e pkg)) expr)))))

(defun evaluate-strategy-signal (strat history)
  (unless (is-safe-trading-time-p (strategy-name strat))
    (return-from evaluate-strategy-signal :hold))
  (when (and history (> (length history) 100))
    (let* ((indicators (strategy-indicators strat))
           (entry-logic (strategy-entry strat))
           (rest-hist (rest history))
           (bindings 
            (loop for ind in indicators
                  append (let ((type (car ind)) (p (cdr ind))
                                (pkg (find-package :swimmy.school)))
                            (case type
                              (sma `((,(intern (format nil "SMA-~d" (car p)) pkg) ,(ind-sma (car p) history))
                                     (,(intern (format nil "SMA-~d-PREV" (car p)) pkg) ,(ind-sma (car p) rest-hist))))
                              (ema `((,(intern (format nil "EMA-~d" (car p)) pkg) ,(ind-ema (car p) history))
                                     (,(intern (format nil "EMA-~d-PREV" (car p)) pkg) ,(ind-ema (car p) rest-hist))))
                              (rsi `((,(intern (format nil "RSI-~d" (car p)) pkg) ,(ind-rsi (car p) history))
                                     (,(intern (format nil "RSI-~d-PREV" (car p)) pkg) ,(ind-rsi (car p) rest-hist))))
                              (cci `((,(intern (format nil "CCI-~d" (car p)) pkg) ,(ind-cci (car p) history))
                                     (,(intern (format nil "CCI-~d-PREV" (car p)) pkg) ,(ind-cci (car p) rest-hist))))
                              (atr `((,(intern (format nil "ATR-~d" (car p)) pkg) ,(ind-atr (car p) history))))
                              (macd (multiple-value-bind (m s) (ind-macd (first p) (second p) (third p) history)
                                      (multiple-value-bind (pm ps) (ind-macd (first p) (second p) (third p) rest-hist)
                                        `((,(intern "MACD-LINE" pkg) ,m) (,(intern "SIGNAL-LINE" pkg) ,s) 
                                          (,(intern "MACD-LINE-PREV" pkg) ,pm) (,(intern "SIGNAL-LINE-PREV" pkg) ,ps)))))
                              (bb (multiple-value-bind (m u l) (ind-bb (first p) (second p) history)
                                    (multiple-value-bind (pm pu pl) (ind-bb (first p) (second p) rest-hist)
                                      (let ((dev (second p)))
                                        `((,(intern (format nil "BB-MIDDLE-~d" dev) pkg) ,m)
                                          (,(intern (format nil "BB-UPPER-~d" dev) pkg) ,u)
                                          (,(intern (format nil "BB-LOWER-~d" dev) pkg) ,l)
                                          (,(intern (format nil "BB-MIDDLE-~d-PREV" dev) pkg) ,pm)
                                          (,(intern (format nil "BB-UPPER-~d-PREV" dev) pkg) ,pu)
                                          (,(intern (format nil "BB-LOWER-~d-PREV" dev) pkg) ,pl)
                                          (,(intern "BB-MIDDLE" pkg) ,m) (,(intern "BB-UPPER" pkg) ,u) (,(intern "BB-LOWER" pkg) ,l)
                                          (,(intern "BB-MIDDLE-PREV" pkg) ,pm) (,(intern "BB-UPPER-PREV" pkg) ,pu) (,(intern "BB-LOWER-PREV" pkg) ,pl))))))
                              (stoch (let ((k (ind-stoch (first p) (second p) history))
                                           (pk (ind-stoch (first p) (second p) rest-hist)))
                                      `((,(intern "STOCH-K" pkg) ,k) (,(intern "STOCH-K-PREV" pkg) ,pk) 
                                        (,(intern "STOCH-D" pkg) 50) (,(intern "STOCH-D-PREV" pkg) 50))))
                              (t 
                               (format t "[L] ⚠️ Unknown indicator type in ~a: ~a~%" (strategy-name strat) type)
                               nil)))))))
      (let ((pkg (find-package :swimmy.school)))
        (push `(,(intern "CLOSE" pkg) ,(candle-close (first history))) bindings)
        (push `(,(intern "CLOSE-PREV" pkg) ,(candle-close (second history))) bindings)
        (push `(,(intern "HIGH" pkg) ,(candle-high (first history))) bindings)
        (push `(,(intern "HIGH-PREV" pkg) ,(candle-high (second history))) bindings)
        (push `(,(intern "LOW" pkg) ,(candle-low (first history))) bindings)
        (push `(,(intern "LOW-PREV" pkg) ,(candle-low (second history))) bindings)
        
        (multiple-value-bind (sec min hour day month year dow) (decode-universal-time (get-universal-time))
          (declare (ignore sec day month year dow))
          (push `(,(intern "HOUR" pkg) ,hour) bindings)
          (push `(,(intern "MINUTE" pkg) ,min) bindings)
          (let ((is-gotobi (if (fboundp (intern "GOTOBI-DAY-P" pkg))
                               (if (funcall (intern "GOTOBI-DAY-P" pkg)) t nil)
                               nil)))
            (push `(,(intern "GOTOBI-P" pkg) ,is-gotobi) bindings))))
      
      (setf bindings (remove-duplicates bindings :key #'car :from-end t))
      
      (let* ((pkg (find-package :swimmy.school))
             (transformed-logic (transform-cross-calls-helper entry-logic pkg)))
        (handler-case
            (locally (declare (sb-ext:muffle-conditions style-warning))
              (let ((entry-result (eval `(let ,bindings ,transformed-logic))))
                (cond
                  (entry-result :buy)
                  ((and (strategy-exit strat)
                        (eval `(let ,bindings ,(transform-cross-calls-helper (strategy-exit strat) pkg)))) :sell)
                  (t :hold))))
          (error (e) 
            (format t "[L] Eval error ~a: ~a~%" (strategy-name strat) e)
            :hold)))))
