import json
import os


def generate_lisp_code():
    json_path = "strategies_optimized.json"
    output_path = "src/lisp/strategies/strategies-recruits.lisp"

    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found")
        return

    with open(json_path, "r") as f:
        data = json.load(f)

    recruits = [s for s in data if s.get("name", "").startswith("RECRUIT-")]

    # Limit to top 20 to avoid bloating the system initially
    recruits = recruits[:20]

    print(f"Found {len(recruits)} recruits. Generating Lisp code...")

    lisp_content = """;;; strategies-recruits.lisp
;;; GENERATED BY ANTI-GRAVITY RECRUITMENT PROTOCOL
;;; New strategies recruited from the Evolutionary Gap.

(in-package :swimmy.school)

(defun get-recruit-strategies ()
  (list"""

    for s in recruits:
        name = s.get("name")
        sl = s.get("sl", 0.05)
        tp = s.get("tp", 0.10)
        tf = s.get("timeframe", 60)
        if isinstance(tf, str):
            if tf == "M1":
                tf = 1
            elif tf == "M5":
                tf = 5
            elif tf == "M15":
                tf = 15
            elif tf == "M30":
                tf = 30
            elif tf == "H1":
                tf = 60
            elif tf == "H4":
                tf = 240
            elif tf == "D1":
                tf = 1440
            elif tf == "W1":
                tf = 10080
            else:
                tf = 60

        ind_type = s.get("indicator_type", "sma")

        # Logic Construction based on Type
        indicators = "'()"
        entry = "'()"
        exit = "'()"

        if ind_type == "sma":
            s_short = s.get("sma_short", 10)
            s_long = s.get("sma_long", 20)
            indicators = f"'((sma {s_short}) (sma {s_long}))"
            entry = f"'(cross-above sma-{s_short} sma-{s_long})"
            exit = f"'(cross-below sma-{s_short} sma-{s_long})"
        elif ind_type == "ema":
            s_short = s.get("sma_short", 10)  # JSON uses same key
            s_long = s.get("sma_long", 20)
            indicators = f"'((ema {s_short}) (ema {s_long}))"
            entry = f"'(cross-above ema-{s_short} ema-{s_long})"
            exit = f"'(cross-below ema-{s_short} ema-{s_long})"
        elif ind_type == "rsi":
            period = s.get("sma_short", 14)  # Reuse key
            indicators = f"'((rsi {period}))"
            entry = f"'(< rsi-{period} 30)"
            exit = f"'(> rsi-{period} 70)"

        lisp_chunk = f"""
      (make-strategy :name "{name}"
        :indicators {indicators}
        :entry {entry}
        :exit {exit}
        :sl {sl:.4f} :tp {tp:.4f} :volume 0.01
        :category :recruit :timeframe {tf})"""

        lisp_content += lisp_chunk

    lisp_content += "))\n"

    with open(output_path, "w") as f:
        f.write(lisp_content)

    print(f"✅ Generated {output_path} with {len(recruits)} strategies.")


if __name__ == "__main__":
    generate_lisp_code()
