import re
import os

FILE_PATH = "src/lisp/strategies/strategies-dynamic.lisp"


def fix_ghosts():
    if not os.path.exists(FILE_PATH):
        print(f"File not found: {FILE_PATH}")
        return

    with open(FILE_PATH, "r") as f:
        content = f.read()

    # Regex to find orphaned (defstrategy ...) at the start of a line
    # We look for (defstrategy ... :regime-filter t)
    # capturing the inner content.
    # We allow whitespace before the closing paren.

    # Pattern explanation:
    # ^\(defstrategy       : Start of line, (defstrategy
    #  (.*?)               : Content (name, slots) - non-greedy
    # :regime-filter t\)   : End marker
    #
    # NOTE: This assumes specific ordering and presence of :regime-filter t.
    # Strategies generated by recruit_elite.py (orphans) seem to have it.

    pattern = re.compile(
        r"^\(defstrategy (.*?):regime-filter t\)", re.DOTALL | re.MULTILINE
    )

    def replacer(match):
        body = match.group(1)
        # We assume the matching stopped at t).
        # We need to reconstruct.
        return f"(push \n  (defstrategy {body}:regime-filter t)\n  *strategy-knowledge-base*)"

    new_content, count = pattern.subn(replacer, content)

    if count > 0:
        print(f"👻 Fixed {count} ghost strategies!")
        with open(FILE_PATH, "w") as f:
            f.write(new_content)
    else:
        print("✅ No ghosts found (or pattern mismatch).")


if __name__ == "__main__":
    fix_ghosts()
