#!/usr/bin/env python3
import json
import os
import sys
from datetime import datetime

# Configuration
INPUT_JSON = "strategies_optimized.json"
OUTPUT_LISP = "src/lisp/school/school-optimized-params.lisp"

HEADER = """;;; school-optimized-params.lisp
;;; GENERATED BY tools/generate_lisp_params.py
;;; DO NOT EDIT MANUALLY.
;;; Generated at: {date}

(in-package :swimmy.school)

(defparameter *optimized-params*
  '(
"""

FOOTER = """   ))

(defun apply-optimized-params ()
  "Apply optimized parameters to the strategy knowledge base."
  (format t "[OPTIMIZER] 🧬 Applying ~d optimized parameter sets...~%" (length *optimized-params*))
  (dolist (params *optimized-params*)
    (let* ((name (getf params :name))
           (strat (find-strategy name)))
      (if strat
          (progn
            ;; Update Params
            (setf (strategy-timeframe strat) (getf params :timeframe))
            (setf (strategy-sl strat) (getf params :sl))
            (setf (strategy-tp strat) (getf params :tp))
            
            ;; Update Indicators (SMA-X)
            (let ((short (getf params :sma-short))
                  (long-p (getf params :sma-long)))
              (setf (strategy-indicators strat)
                    (list (format nil "SMA-~d" short)
                          (format nil "SMA-~d" long-p)))
              ;; Update entry logic text if needed (assuming simple cross)
              (setf (strategy-entry strat)
                    (format nil "CROSS SMA ~d ~d" short long-p)))
            
            ;; Mark Generation/Update
            (setf (strategy-generation strat) (1+ (strategy-generation strat)))
            
            ;; (format t "[OPTIMIZER] Updated ~a (TF:~d SL:~,3f TP:~,3f)~%" name (getf params :timeframe) (getf params :sl) (getf params :tp))
            )
          ;; Strategy not found - could be arecruit
          (format t "[OPTIMIZER] ⚠️ Strategy ~a not found in KB (Skipping)~%" name)))))
"""


def generate_lisp():
    if not os.path.exists(INPUT_JSON):
        print(f"❌ {INPUT_JSON} not found.")
        sys.exit(1)

    with open(INPUT_JSON, "r") as f:
        data = json.load(f)

    with open(OUTPUT_LISP, "w") as f:
        f.write(HEADER.format(date=datetime.now().isoformat()))

        for strat in data:
            name = strat.get("name")
            tf = strat.get("timeframe", 15)
            sl = strat.get("sl", 0.05)
            tp = strat.get("tp", 0.05)
            sma_short = strat.get("sma_short", 10)
            sma_long = strat.get("sma_long", 20)

            # Write S-Expression
            line = f'    (:name "{name}" :timeframe {tf} :sl {sl} :tp {tp} :sma-short {sma_short} :sma-long {sma_long})\n'
            f.write(line)

        f.write(FOOTER)

    print(f"✅ Generated {OUTPUT_LISP} with {len(data)} strategies.")


if __name__ == "__main__":
    generate_lisp()
